version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo1234
      ME_CONFIG_MONGODB_URL: mongodb://Mongo:Mongo1234@localhost:27016/?authMechanism=DEFAULT