version: '3.1'

services:

  db-master:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Mongo
      MONGO_INITDB_ROOT_PASSWORD: Mongo1234
    ports:
      - "8082:27017"
    networks:
      - default
    volumes:
      - mongo-db-master:/data/db

  app-server-master:
    image:  ${DOCKER_HUB_USERNAME}/moonlight-project:latest
    environment:
      MONGO_USER: Mongo
      MONGO_PASSWORD: Mongo1234
      MONGO_PORT: 27016
      PORT: 8081
      ENV: master
    ports:
      - '8081:3000'
    restart: always
    networks:
      - default
    depends_on:
      - db-master

volumes:
  mongo-db-master: