name: deploy master
on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: master
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      MONGO_USER: Mongo
      MONGO_PASSWORD: Mongo1234
      MONGO_PORT: 27016
      PORT: 8081
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/moonlight-project:latest
      -
        name: Prepare the docker-compose run
        run: |
              ls -l
      - 
        name: Prepare docker-compose run
        run: |
              mkdir moonlight-project
              cp docker-compose.yml moonlight-project/docker-compose.yml
              cd moonlight-project
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.yml down
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.yml pull
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.yml up -d